# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - main
      - issue-*
  pull_request:
    branches: 
      - main
      - issue-*
jobs:
  start:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Restful e-commerce App
        uses: ./
        with:
          build: npm ci
          start: npm start
          wait-on: 'http://localhost:3004'

      - name: Run Unit Tests
        run: npm test

      - name: stop all instances of node
        run: killall node
    
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results        
          path: ${{ github.workspace }}/reports/test-results.json
          reporter: 'mocha-json'

    