# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - main
      - issue-*
  pull_request_target:
    branches: 
      - main
      - issue-*
jobs:
  Build_App_using_node_and_Run_Tests:
    name: Build Service using Node and run unit tests

    runs-on: ubuntu-latest
    permissions:
      checks: write
    
    env:
      AUTH_USERNAME: ${{secrets.AUTH_USERNAME}}
      AUTH_PASSWORD: ${{secrets.AUTH_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install the dependencies
      run: npm ci

    - name: Create .env from secrets
      run: |
        cat > .env <<'EOF'
        AUTH_USERNAME=${{ secrets.AUTH_USERNAME }}
        AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        EOF

    - name: Start the app in Background and Wait for Server to be available
      run: npm start && npx wait-on http://localhost:3004 & 

    - name: Run the tests
      run: npm test
  
    - name: Kill all instances of node
      run: pkill -f node
    
    - name: Test Report
      uses: dorny/test-reporter@v3
      if: success() || failure()
      with:
          name: Test Report
          path: ${{ github.workspace }}/reports/test-results.json
          reporter: 'mocha-json'

  Build_App_Docker_Compose_and_Run_Test:
    name: Build Service using Docker Compose and run unit tests

    runs-on: ubuntu-latest
    permissions:
      checks: write
    
    env:
      AUTH_USERNAME: ${{secrets.AUTH_USERNAME}}
      AUTH_PASSWORD: ${{secrets.AUTH_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install the dependencies
      run: npm ci

    - name: Create .env from secrets
      run: |
        cat > .env <<'EOF'
        AUTH_USERNAME=${{ secrets.AUTH_USERNAME }}
        AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        EOF

    - name: Start the service using Docker Compose
      run: docker compose -f docker-compose-ecommerce.yml up -d
    
    - name: Wait for service to be available
      run: npx wait-on http://localhost:3004 &

    - name: Run the unit tests
      run: npm run unit-test

    - name: Stop the service
      if: always()
      run: docker compose -f docker-compose-ecommerce.yml down --remove-orphans